version: '3'
services:
  ma6-main:
    image: 2swo/ma6-menbosha-front
    ports:
      - '8080:80'
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Asia/Seoul
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certbot_data:/etc/letsencrypt
    command: ['nginx', '-g', 'daemon off;']

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot_data:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do certbot certonly --nginx --non-interactive --agree-tos --email swlee14520@gmail.com -d menbosha.kr; sleep 12h & wait $${!}; done;"
